### PR TITLE
Update OpenCL LUT type to uchar buffer

### PR DESCRIPTION
**Pull request by hansely**
OpenCL image1d type, the original type for LUT, has been deprecated which causes failures in MI300 system.
Updated the data type to use uchar buffer instead as in HIP backend

### CODE REVIEW

**Comment by kiritigowda** [comment]
@hansely - CI failing for OpenCL compile. http://math-ci.amd.com/blue/organizations/jenkins/mainline%2Fprecheckin%2FMIVisionX/detail/PR-1442/1/pipeline/980/

```
[ 78%] Building CXX object amd_openvx_extensions/amd_opencv/CMakeFiles/vx_opencv.dir/source/OpenCV_gaussianBlur.cpp.o
/mnt/m2m_nobackup/jenkins_home/workspace/ine_precheckin_MIVisionX_PR-1442/q0pAqentn/OpenCL/mivisionx/utilities/loom_shell/loom_shell_util.cpp:519:2: error: unknown type name 'clEnqueueWaitSignalAMD_fn'
  519 |         clEnqueueWaitSignalAMD_fn clEnqueueWaitSignalAMD = (clEnqueueWaitSignalAMD_fn)clGetExtensionFunctionAddressForPlatform(platform_id[platform_index], "clEnqueueWaitSignalAMD");
      |         ^
/mnt/m2m_nobackup/jenkins_home/workspace/ine_precheckin_MIVisionX_PR-1442/q0pAqentn/OpenCL/mivisionx/utilities/loom_shell/loom_shell_util.cpp:519:54: error: use of undeclared identifier 'clEnqueueWaitSignalAMD_fn'; did you mean 'clEnqueueWaitSignalAMD'?
  519 |         clEnqueueWaitSignalAMD_fn clEnqueueWaitSignalAMD = (clEnqueueWaitSignalAMD_fn)clGetExtensionFunctionAddressForPlatform(platform_id[platform_index], "clEnqueueWaitSignalAMD");
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                             clEnqueueWaitSignalAMD
/mnt/m2m_nobackup/jenkins_home/workspace/ine_precheckin_MIVisionX_PR-1442/q0pAqentn/OpenCL/mivisionx/utilities/loom_shell/loom_shell_util.cpp:519:28: note: 'clEnqueueWaitSignalAMD' declared here
  519 |         clEnqueueWaitSignalAMD_fn clEnqueueWaitSignalAMD = (clEnqueueWaitSignalAMD_fn)clGetExtensionFunctionAddressForPlatform(platform_id[platform_index], "clEnqueueWaitSignalAMD");
      |                                   ^
/mnt/m2m_nobackup/jenkins_home/workspace/ine_precheckin_MIVisionX_PR-1442/q0pAqentn/OpenCL/mivisionx/utilities/loom_shell/loom_shell_util.cpp:519:80: error: expected ';' at end of declaration
  519 |         clEnqueueWaitSignalAMD_fn clEnqueueWaitSignalAMD = (clEnqueueWaitSignalAMD_fn)clGetExtensionFunctionAddressForPlatform(platform_id[platform_index], "clEnqueueWaitSignalAMD");
      |                                                                                       ^
```

**Comment by hansely** [comment]
> @hansely - CI failing for OpenCL compile. http://math-ci.amd.com/blue/organizations/jenkins/mainline%2Fprecheckin%2FMIVisionX/detail/PR-1442/1/pipeline/980/
> 
> ```
> [ 78%] Building CXX object amd_openvx_extensions/amd_opencv/CMakeFiles/vx_opencv.dir/source/OpenCV_gaussianBlur.cpp.o
> /mnt/m2m_nobackup/jenkins_home/workspace/ine_precheckin_MIVisionX_PR-1442/q0pAqentn/OpenCL/mivisionx/utilities/loom_shell/loom_shell_util.cpp:519:2: error: unknown type name 'clEnqueueWaitSignalAMD_fn'
>   519 |         clEnqueueWaitSignalAMD_fn clEnqueueWaitSignalAMD = (clEnqueueWaitSignalAMD_fn)clGetExtensionFunctionAddressForPlatform(platform_id[platform_index], "clEnqueueWaitSignalAMD");
>       |         ^
> /mnt/m2m_nobackup/jenkins_home/workspace/ine_precheckin_MIVisionX_PR-1442/q0pAqentn/OpenCL/mivisionx/utilities/loom_shell/loom_shell_util.cpp:519:54: error: use of undeclared identifier 'clEnqueueWaitSignalAMD_fn'; did you mean 'clEnqueueWaitSignalAMD'?
>   519 |         clEnqueueWaitSignalAMD_fn clEnqueueWaitSignalAMD = (clEnqueueWaitSignalAMD_fn)clGetExtensionFunctionAddressForPlatform(platform_id[platform_index], "clEnqueueWaitSignalAMD");
>       |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
>       |                                                             clEnqueueWaitSignalAMD
> /mnt/m2m_nobackup/jenkins_home/workspace/ine_precheckin_MIVisionX_PR-1442/q0pAqentn/OpenCL/mivisionx/utilities/loom_shell/loom_shell_util.cpp:519:28: note: 'clEnqueueWaitSignalAMD' declared here
>   519 |         clEnqueueWaitSignalAMD_fn clEnqueueWaitSignalAMD = (clEnqueueWaitSignalAMD_fn)clGetExtensionFunctionAddressForPlatform(platform_id[platform_index], "clEnqueueWaitSignalAMD");
>       |                                   ^
> /mnt/m2m_nobackup/jenkins_home/workspace/ine_precheckin_MIVisionX_PR-1442/q0pAqentn/OpenCL/mivisionx/utilities/loom_shell/loom_shell_util.cpp:519:80: error: expected ';' at end of declaration
>   519 |         clEnqueueWaitSignalAMD_fn clEnqueueWaitSignalAMD = (clEnqueueWaitSignalAMD_fn)clGetExtensionFunctionAddressForPlatform(platform_id[platform_index], "clEnqueueWaitSignalAMD");
>       |                                                                                       ^
> ```

This is actually not from this PR. It should be one of the previous PR.

**Comment by hansely** [comment]
@kiritigowda Reopened #1365

**Comment by hansely** [comment]
@kiritigowda This can be merged once @rrawther  approves it

**Review by kiritigowda — APPROVED** [review]

**Pull request merged**
