### PR TITLE
Fix exposure compensation kernel

### PR DESCRIPTION
**Pull request by zichguan-amd**
Fix kernel build failure in https://github.com/ROCm/MIVisionX/issues/396

### CODE REVIEW

**Comment by kiritigowda** [comment]
@hansely can you take a look at this?

**Comment by kiritigowda** [comment]
@hansely can you please test this and approve? Thanks!

**Comment by hansely** [comment]
Still observing the issue with the change
```
loom_shell loomStitch-sample1.txt 
loom_shell 0.9.9 [loomsl 0.9.9]
... processing commands from loomStitch-sample1.txt
..ls_context context[1] created
..lsCreateContext: created context context[0]
..lsSetOutputConfig: successful for context[0]
..lsSetCameraConfig: successful for context[0]
OK: OpenVX using GPU device - 0: gfx1100 [OpenCL 2.0 ] [CL_DEVICE_SVM_CAPABILITIES 0 0]
ERROR: OpenVX call failed with status = (-1) at /
MIVisionX/amd_openvx_extensions/amd_loomsl/live_stitch_api.cpp#2758
ERROR: lsInitialize(context[0]) failed (-1) @loomStitch-sample1.txt#24
... exit from loomStitch-sample1.txt
```

**Comment by zichguan-amd** [comment]
@hansely this PR only fixes this ocl build error
```
ERROR: clBuildProgram(0xdc5c00,-cl-std=CL1.2) failed(-11) for com.amd.loomsl.expcomp_compute_gainmatrix
ERROR: OpenVX call failed with status = (-1) at /home/arpu/Work/githubsources/MIVisionX/amd_openvx_extensions/amd_loomsl/live_stitch_api.cpp#2758
ERROR: lsInitialize(context[0]) failed (-1) @loomStitch-sample1.txt#24
```
You can verify that particular kernel `exposure_comp_calc_errorfn_mask` builds correctly with `runcl` after the changes. To get the kernel log, use `AGO_DUMP_GPU` environment variable as specified here https://github.com/ROCm/MIVisionX/blob/ed7a547b81979f257f8d6c458786505c394990a4/amd_openvx/openvx/ago/ago_util_opencl.cpp#L2096-L2097
There are more bugs down the line, and it is expected to fail with 
```
ERROR: OpenVX call failed with status = (-1) at /home/rocm/Documents/loom/MIVisionX/amd_openvx_extensions/amd_loomsl/live_stitch_api.cpp#2758
ERROR: lsInitialize(context[0]) failed (-1) @loomStitch-sample1.txt#24
```

**Comment by hansely** [comment]
@zichguan-amd  Ah I see. I thought it was one single error. Are you going to investigate the issue further and merge the fix to this PR?

**Comment by kiritigowda** [comment]
@zichguan-amd will merge this as part of the fix.

**Review by kiritigowda — APPROVED** [review]

**Pull request merged**
